### ISSUE TITLE
vhba: Fails to build on kernel v5.15

### ISSUE THREAD

**Issue by iam-TJ** [cdemu/cdemu#12]
I build mainline kernels and up through v5.14 the module builds correctly. Today, with v5.15-rc6 it fails to build:
```
DKMS make.log for vhba-20210418 for kernel 5.15.0-rc6-soggy-00004-gfb2264f46ac0-dirty (x86_64)
Mon 18 Oct 21:08:09 BST 2021
make -C /lib/modules/5.15.0-rc6-soggy-00004-gfb2264f46ac0-dirty/build M=/var/lib/dkms/vhba/20210418/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-rc6-soggy-00004-gfb2264f46ac0-dirty'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Debian 10.2.1-6) 10.2.1 20210110
  You are using:           gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  CC [M]  /var/lib/dkms/vhba/20210418/build/vhba.o
/var/lib/dkms/vhba/20210418/build/vhba.c: In function ‘vhba_device_queue’:
/var/lib/dkms/vhba/20210418/build/vhba.c:206:30: error: ‘struct scsi_cmnd’ has no member named ‘request’
  206 |     vcmd->metatag = vcmd->cmd->request->tag;
      |                              ^~
In file included from ./include/linux/printk.h:555,
                 from ./include/linux/kernel.h:19,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /var/lib/dkms/vhba/20210418/build/vhba.c:26:
/var/lib/dkms/vhba/20210418/build/vhba.c: In function ‘vhba_queuecommand’:
/var/lib/dkms/vhba/20210418/build/vhba.c:476:48: error: ‘struct scsi_cmnd’ has no member named ‘request’
  476 |     scmd_dbg(cmd, "queue %p tag %i\n", cmd, cmd->request->tag);
      |                                                ^~
./include/linux/dynamic_debug.h:134:15: note: in definition of macro ‘__dynamic_func_call’
  134 |   func(&id, ##__VA_ARGS__);  \
      |               ^~~~~~~~~~~
./include/linux/dynamic_debug.h:166:2: note: in expansion of macro ‘_dynamic_func_call’
  166 |  _dynamic_func_call(fmt,__dynamic_dev_dbg,   \
      |  ^~~~~~~~~~~~~~~~~~
./include/linux/dev_printk.h:155:2: note: in expansion of macro ‘dynamic_dev_dbg’
  155 |  dynamic_dev_dbg(dev, dev_fmt(fmt), ##__VA_ARGS__)
      |  ^~~~~~~~~~~~~~~
./include/scsi/scsi_device.h:257:2: note: in expansion of macro ‘dev_dbg’
  257 |  dev_dbg(&(sdev)->sdev_gendev, fmt, ##a)
      |  ^~~~~~~
./include/scsi/scsi_device.h:278:4: note: in expansion of macro ‘sdev_dbg’
  278 |    sdev_dbg((scmd)->device, "[%s] " fmt,  \
      |    ^~~~~~~~
/var/lib/dkms/vhba/20210418/build/vhba.c:476:5: note: in expansion of macro ‘scmd_dbg’
  476 |     scmd_dbg(cmd, "queue %p tag %i\n", cmd, cmd->request->tag);
      |     ^~~~~~~~
/var/lib/dkms/vhba/20210418/build/vhba.c:476:48: error: ‘struct scsi_cmnd’ has no member named ‘request’
  476 |     scmd_dbg(cmd, "queue %p tag %i\n", cmd, cmd->request->tag);
      |                                                ^~
./include/linux/dynamic_debug.h:134:15: note: in definition of macro ‘__dynamic_func_call’
  134 |   func(&id, ##__VA_ARGS__);  \
      |               ^~~~~~~~~~~
./include/linux/dynamic_debug.h:166:2: note: in expansion of macro ‘_dynamic_func_call’
  166 |  _dynamic_func_call(fmt,__dynamic_dev_dbg,   \
      |  ^~~~~~~~~~~~~~~~~~
./include/linux/dev_printk.h:155:2: note: in expansion of macro ‘dynamic_dev_dbg’
  155 |  dynamic_dev_dbg(dev, dev_fmt(fmt), ##__VA_ARGS__)
      |  ^~~~~~~~~~~~~~~
./include/scsi/scsi_device.h:257:2: note: in expansion of macro ‘dev_dbg’
  257 |  dev_dbg(&(sdev)->sdev_gendev, fmt, ##a)
      |  ^~~~~~~
./include/scsi/scsi_device.h:281:4: note: in expansion of macro ‘sdev_dbg’
  281 |    sdev_dbg((scmd)->device, fmt, ##a);  \
      |    ^~~~~~~~
/var/lib/dkms/vhba/20210418/build/vhba.c:476:5: note: in expansion of macro ‘scmd_dbg’
  476 |     scmd_dbg(cmd, "queue %p tag %i\n", cmd, cmd->request->tag);
      |     ^~~~~~~~
make[2]: *** [scripts/Makefile.build:277: /var/lib/dkms/vhba/20210418/build/vhba.o] Error 1
make[1]: *** [Makefile:1868: /var/lib/dkms/vhba/20210418/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-rc6-soggy-00004-gfb2264f46ac0-dirty'
make: *** [Makefile:14: modules] Error 2
```
