### ISSUE TITLE
vhba modules fail to build with kernel 6.11

### ISSUE THREAD

**Issue by marillat** [cdemu/cdemu#39]
Debian unstable amd64
GCC 14.2.0

```
DKMS make.log for vhba-20240202 for kernel 6.11.0-1-custom (x86_64)
Mon Sep 16 15:09:02 CEST 2024
make -C /lib/modules/6.11.0-1-custom/build M=/var/lib/dkms/vhba/20240202/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.11.0-1-custom'
  CC [M]  /var/lib/dkms/vhba/20240202/build/vhba.o
/var/lib/dkms/vhba/20240202/build/vhba.c:1087:15: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [-Wincompatible-pointer-types]
 1087 |     .remove = vhba_remove,
      |               ^~~~~~~~~~~
/var/lib/dkms/vhba/20240202/build/vhba.c:1087:15: note: (near initialization for 'vhba_platform_driver.<anonymous>.remove')
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/vhba/20240202/build/vhba.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.11.0-1-custom/Makefile:1926: /var/lib/dkms/vhba/20240202/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.11.0-1-custom'
make: *** [Makefile:14: modules] Error 2
```

**Comment by marillat** [comment]
Thanks for your work.
